### ISSUE TITLE
Genericons not working for new social network links

### ISSUE THREAD

**Issue by riftrid3r** [riftrid3r/wpjen#23]
At the bottom of main page there are social network links with no icon. They need icons. It seems that in the theme css file genericons are referenced. we need to figure out which implementation of this "icons as font" the theme uses, and properly implement the icons. This link seems to be a good jumping off point: https://css-tricks.com/html-for-icon-font-usage/

**Comment by riftrid3r** [comment]
If we click the edit button at the bottom right of this page:
[](http://janichowski.com/wp-admin/customize.php)
we are able to edit the social icons menu "the theme way" in the wordpress "customize" GUI. ok.
after trying several things out here I noticed that the editor here seems to be assign "genericons" via the the the actual domain name in the link field of the customize GUI. And... there is no icons for the sites you are trying to add. I think the quickest fix will be:
* find the svg file for the genericons.
* pick icons that you like that exist already in the svg file for each site.
* manually add those catches to the theme code so that the icons are assigned to links.

(The correct way to implement this is to have the icons associated with an icon field or with the link text field and NOT the url. Alas that is not our problem it is the theme creators problem. The suggested fix above follows the code convention the originator of the theme code has set. Perhaps I will open a ticket over there.)

**Comment by JLAnichowski** [comment]
ok. I have picked out the genericon images(?) I would like used. I could create small image files if placing a .gif or .jpg as a button would work. 
genericon - paintbrush (patreon)
genericon - image (redbubble)
genericon - picture (fine art america)

**Comment by riftrid3r** [comment]
Yeah Thanks. Create JPGs for all the social links including the ones that are there. I will try editing the code. If that doesn't work then we will set up another footer element that does it the old fashioned way with jpg.

**Comment by riftrid3r** [comment]
@JLAnichowski, found it.
[https://github.com/riftrid3r/wpjen/blob/dev/wp-content/themes/wp-portfolio/style.css#L792-L923](url)
AND:
[https://github.com/riftrid3r/wpjen/blob/dev/wp-content/themes/wp-portfolio/font/genericons-regular-webfont.svg?short_path=ef236c1](url)
We add css here:
[http://janichowski.com/wp-admin/customize.php](url)

**Comment by riftrid3r** [comment]
this is the set of icons we are using:
![image](https://user-images.githubusercontent.com/780370/34549785-3839db18-f0c0-11e7-9fea-38116288cece.png)

**Comment by riftrid3r** [comment]
fixed.

**Comment by JLAnichowski** [comment]
you are awesome!
